apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "localhost"
    http:
      paths:
      - backend:
          service:
            name: caddy-service
            port:
              name: http
        path: /
        pathType: Prefix
